### ISSUE TITLE
Contact the maintainers of storybook

### ISSUE THREAD

**Issue by ndelangen** [z4o4z/storybook-addon-events#1]
Hey! awesome addon, 

Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 
I'm also interested in making this a core addon!

❤️ storybook team

**Comment by z4o4z** [comment]
Hi! I'm already there)

How can I help you with it?
> I'm also interested in making this a core addon!

**Comment by ndelangen** [comment]
Let's talk about that on slack 😄
